name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '23'
      - uses: pnpm/action-setup@v2
        with:
          version: '9.15.0'
      - run: pnpm install
      - run: |
          cd packages/hula-emojis
          pnpm update
          pnpm build
          npm adduser --registry https://registry.npmjs.org/ --scope=@btmuli
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
